### PR TITLE
New TIki auth driver, a great way to integrate BlueBox into your Tiki site

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
This is what we'll be using in Tiki Suite.  Can't wait to see what is possible after it is integrated.

### CODE REVIEW

**Comment by J-O-N** [comment]
Hi Robert!

Nice work, we are reviewing your work and will post back soon.

**Comment by robertleeplummerjr** [comment]
Any reason why this has not been merged yet?

**Comment by tm1000** [comment]
Because @J-O-N  never tested it I believe?

**Comment by tm1000** [comment]
I'm tired of waiting.

**Comment by robertleeplummerjr** [comment]
We did spend a lot of time and money on this one, it is a really nice way
of integrating a phone system with Tiki, and may be edge case for the time
being.

On Wed, Oct 17, 2012 at 3:35 PM, Andrew Nagy notifications@github.comwrote:

> I'm tired of waiting.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/2600hz/bluebox/pull/26#issuecomment-9540787.

## 

Robert Plummer

**Comment by tm1000** [comment]
Merged now. :-)

**Comment by robertleeplummerjr** [comment]
You da man!  Look for a few more ;).  We want to make this product shine!

On Wed, Oct 17, 2012 at 3:37 PM, Andrew Nagy notifications@github.comwrote:

> Merged now. :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/2600hz/bluebox/pull/26#issuecomment-9540837.

## 

Robert Plummer

**Pull request merged**
