### PR TITLE
Update modules/backup-1.0/libraries/Backup.php

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
One more go at pull request.  This now works with php 5.4+.  Problem was that $database was not being set in method mysqlImport, also the syntax for concatenating is not '+' but rather '.', which I changed as well for the connection string to work.

### CODE REVIEW

**Comment by tm1000** [comment]
If you are modifying the same file please combine pull requests

**Comment by robertleeplummerjr** [comment]
I already cancelled out the old one, I can't just give you the new one?

On Sat, Oct 6, 2012 at 5:58 PM, Andrew Nagy notifications@github.comwrote:

> If you are modifying the same file please combine pull requests
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/2600hz/bluebox/pull/47#issuecomment-9202864.

## 

Robert Plummer

**Comment by tm1000** [comment]
I still see two active pull requests for the same file. You closed one but there's still another

**Comment by robertleeplummerjr** [comment]
Let me find and close the first.

**Comment by robertleeplummerjr** [comment]
Sorry about the delay, this should be the only remaining one left open.

**Comment by robertleeplummerjr** [comment]
I have another pull request I'd like to put in, any chance this will be merged soon?

**Comment by tm1000** [comment]
Done

**Comment by robertleeplummerjr** [comment]
Thanks Andrew!

On Wed, Oct 17, 2012 at 3:31 PM, Andrew Nagy notifications@github.comwrote:

> Done
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/2600hz/bluebox/pull/47#issuecomment-9540633.

## 

Robert Plummer

**Pull request merged**
