### PR TITLE
Add docs 1

### PR DESCRIPTION
**Pull request by Jaybee-**
This is some documentation on how to get an approx. 10-fold speed increase for the directory listing. It is not installed by default.

### CODE REVIEW

**Comment by J-O-N** [comment]
Not sure quite how to commit this one, I will leave it open as a reminder until we find it a proper home.

**Comment by J-O-N** [comment]
I'm thinking a wiki article most likely, thoughts?

**Comment by Jaybee-** [comment]
A wiki article would be an excellent home.

**Comment by Jaybee-** [comment]
This now lives in WikiWorld.

**Pull request closed without merging**
